### PR TITLE
Add allowfullscreen binding to embedVideo directive

### PR DESCRIPTION
**Pull request by alejandroiglesias**
This allows, for example, to disable fullscreen on Vimeo.

### CODE REVIEW

**Comment by alejandroiglesias** [comment]
Rebased to latest `master` and fixed code to work on Angular 1.2+. Tests pass now.

**Comment by alejandroiglesias** [comment]
@erost: did you have a chance to look at this?

**Comment by erost** [comment]
@alejandroiglesias thx for the PR!

**Comment by alejandroiglesias** [comment]
@erost you're welcome! And thanks for integrating the changes.

**Pull request merged**
